#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

DEFAULT_USER=luis

#export CLICOLOR=1
#export LSCOLORS=ExFxCxDxBxegedabagacad

#export PATH=/usr/local/bin:$PATH:~/Software/bin
#export PATH="$PATH:~/Software/android-sdk/tools:~/Software/android-sdk/platform-tools"

#alias e=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient

#export PATH="/Users/luis/Software/narwhal/bin:$PATH"
#export PATH="/Users/luis/.cabal/bin:$PATH"

#CIM_HOME=/Users/luis/.cim; [ -s '/Users/luis/.cim/init.sh' ] && . '/Users/luis/.cim/init.sh'
